Cancan
dniman/qna pull request #18
Opened 2020-09-14 18:40 UTC by dniman

2020-09-15 10:09 UTC, IvanShamatov requested changes
В целом норм, небольшие правки стоит сделать.

2020-09-15 10:09 UTC, IvanShamatov commented on app/controllers/user/bounties_controller.rb
> +  skip_authorization_check
не понял этой записи, а зачем скипать авторизацию ресурса, если ты её не добавлял в ApplicationController?

2020-09-15 10:09 UTC, IvanShamatov commented on app/controllers/users_controller.rb
> +  skip_authorization_check only: :enter_email
очень очень очень плохая практика делать двойные отрицания, 
Вот тут как бы должна работать проверка, но мы все же её скипаем, но все же только для enter_email

Тут действует правило такое же как с before_action. Выполняется всегда и мы перечисляем only.
(Исключением из этого правила является authenticate_user! при котором except целенаправленый)

А соответственно если у нас какой-то колбек начинается со skip, то он должен быть с except. Т.е. скип -- является дефолтным поведением, и мы только указываем, для чего оно не должно срабатывать, чтобы если вдруг добавляется еще один экшн в контроллере, то мы ручками вписали бы его и во все колбеки.

2020-09-15 10:09 UTC, IvanShamatov commented on app/models/ability.rb
> +    end
не вижу использования admin_abilities где-то

2020-09-15 10:09 UTC, IvanShamatov commented on spec/rails_helper.rb
> +  #config.before(:each, truncation: true) do
закомменчено, потому что нужно удалить или оставить? тут нужно принять решение, и если код не нужен -- от него избавляются

2020-09-15 10:09 UTC, IvanShamatov commented on spec/rails_helper.rb
> +require "cancan/matchers"
сохрани, пожалуйста, рубокоповский стиль с одинарными кавычками.

2020-09-15 11:28 UTC, dniman commented on app/models/ability.rb
> +    end
admin был только в примере, в проекте не думаю, что он нужен сейчас

2020-09-15 11:57 UTC, IvanShamatov commented on app/models/ability.rb
> +    end
тогда стоит убрать

2020-09-16 12:16 UTC, vkurennov approved these changes

2020-09-16 12:16 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
тут надо все 3 формата поддерживать: для html редиретк - ок, а для js и json хорошо бы вернуть 403 статус (forbidden)

2020-09-16 12:16 UTC, vkurennov commented on app/controllers/files_controller.rb
> +    authorize!(params[:action].to_sym, @attachment)
ну тут авторизация не для произвольного экшена должна быть, а конкретно для destroy, поэтому и в authorize! стоит указать именно destroy

2020-09-16 12:16 UTC, vkurennov commented on app/models/ability.rb
> +      answer.question.user_id == user.id
тут и далее стоит использовать метод проверки автора из модели User

2020-09-16 12:34 UTC, merged