Api
dniman/qna pull request #19
Opened 2020-09-23 20:34 UTC by dniman

2020-09-24 08:49 UTC, IvanShamatov requested changes
Надо переработать.

2020-09-24 08:49 UTC, IvanShamatov commented on app/controllers/api/v1/answers_controller.rb
> +class Api::V1::AnswersController < Api::V1::BaseController
https://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html#method-i-acronym
Если заиспользовать инфлектор, то можно будет называть нормально неймспейс API большими буквами, и рельса будет правлиьно подгружать эти классы

2020-09-24 08:49 UTC, IvanShamatov commented on app/controllers/api/v1/answers_controller.rb
> +    @answer.update(answer_params) if current_resource_owner.author_of?(@answer)
Ты же сделал авторизацию через cancan, проверка на авторство является частью подобной проверки.

2020-09-24 08:49 UTC, IvanShamatov commented on app/controllers/api/v1/answers_controller.rb
> +    @answer.destroy if current_resource_owner.author_of?(@answer)
cancan

2020-09-24 08:49 UTC, IvanShamatov commented on app/controllers/api/v1/answers_controller.rb
> +    def find_question
неконсистентность в нейминге. Пусть либо оба метода будут find_... или set_...

2020-09-24 08:49 UTC, IvanShamatov commented on app/controllers/api/v1/answers_controller.rb
> +      @answer = Answer.find(params[:id])
поскольку у нас вложенные ресурсы, то я всегда рекомендую делать еще и одновременно проверку на пренадлежность вложенного ресурса к родителю
`@answer = @question.answers.find(params[:id])` 
Иначе можно где-то об этом забыть и хакер сможет получить к ресурсу, который к родителю не относится

2020-09-24 08:49 UTC, IvanShamatov commented on app/controllers/api/v1/questions_controller.rb
> +    @question.update(question_params) if current_resource_owner.author_of?(@question)
cancan

2020-09-24 08:49 UTC, IvanShamatov commented on app/controllers/api/v1/questions_controller.rb
> +    @question.destroy if current_resource_owner.author_of?(@question)
cancan

2020-09-24 08:49 UTC, IvanShamatov commented on app/controllers/application_controller.rb
> +  include CheckAuthorization
ты либо это зря добавил, либо забыл удалить код ниже

2020-09-24 08:49 UTC, IvanShamatov commented on app/controllers/concerns/exception_handler.rb
> +    rescue_from ActiveRecord::RecordNotFound do |exception|
Выглядит так, будто этот код должен либо больше форматов обслуживать, либо он актуален только для API, тогда его есть смысл инклудить именно в API...ApplicationController

2020-09-24 08:49 UTC, IvanShamatov commented on app/controllers/concerns/response.rb
> +module Response
module JSONResponse (см рефлектор) будет хорошим модулем для одного этого метода

2020-09-24 08:49 UTC, IvanShamatov commented on app/controllers/concerns/response.rb
> +    return render json: object, status: status, each_serializer: options[:serializer] if options.has_key?(:serializer)
не совсем корректная логика. Ты подразумеваешь, что если передан ключ, то у тебя коллекция, а нужно как раз таки это и узнавать
Если object --коллекция?, тогда смотрим ключ сериалайзера, если его нет, то просто рендерим json как умеем, потому что each_serializer не применим к одному интансу (насколько мне помнится).

https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/general/rendering.md#1-for-a-resource 
однако реально иногда нужно передавать сериалайзер для одного рекорда.

Другой разработчик приходит в твой проект, смотрит, что можно передать ключ serializer, втыкает свой сериалайзер, и тут у него ломается приложение

2020-09-24 08:49 UTC, IvanShamatov commented on app/models/link.rb
> +  default_scope { order(id: :desc).order(:created_at) }
НИКОГДА не используй default_scope. Сам дефолт скоуп работает как надо, проблемы начинаются. когда тебе нужно отказаться от дефолтного скоупа и ты используешь unscoped. И поверь, вот такая сортировка вовсе не обязана быть везде и всегда.

2020-09-24 08:49 UTC, IvanShamatov commented on app/serializers/answer_serializer.rb
> +    object.files.inject([]) do |arr, file|
наверно ты тут забыл про N+1 запрос, который генерируется таким образом. используй with_attached_files

2020-09-24 08:49 UTC, IvanShamatov commented on app/serializers/answer_serializer.rb
> +    object.files.inject([]) do |arr, file|
да и inject тут излишен, если тебе нужен массив
`object.with_attached_files.files.map { |file| rails_blob_path(file, only_path: true) }`

2020-09-24 08:49 UTC, IvanShamatov commented on app/serializers/question_serializer.rb
> +    object.files.inject([]) do |arr, file|
см выше

2020-09-24 08:49 UTC, IvanShamatov commented on app/serializers/user_serializer.rb
> +class UserSerializer < ActiveModel::Serializer
для others нужен другой сериалайзер, чтобы оно не отдавало список других пользователей, в котором фигурирует флаг admin

2020-09-24 08:49 UTC, IvanShamatov commented on spec/api/v1/answers_spec.rb
> +        do_request(method, api_path, options)
Запрос-то можно и один раз сделать, а проверить 4, зачем 4 запроса делать?

2020-09-24 08:49 UTC, IvanShamatov commented on spec/api/v1/answers_spec.rb
> +    let(:options) { { params: { access_token: access_token.token } } }
какая-то копипаста... не смог найти разницу между строчками 52 и 58

2020-09-24 08:49 UTC, IvanShamatov commented on spec/api/v1/answers_spec.rb
> +    it_behaves_like 'API Unauthorizable' do
выглядит как оба и Authorizable и Unaauthorizable про одно и то же. Не хочешь их совместить?

2020-09-24 08:49 UTC, IvanShamatov commented on spec/api/v1/answers_spec.rb
> +    it_behaves_like 'API Unauthorizable' do
SharedExamples лучше всего размещать наверху контекста или даже всего спека

2020-09-24 08:49 UTC, IvanShamatov commented on spec/api/v1/answers_spec.rb
> +        do_request(method, api_path, options)
про это был коммент выше

2020-09-24 08:49 UTC, IvanShamatov commented on spec/api/v1/answers_spec.rb
> +          expect(link_response[attr]).to eq link.send(attr).as_json
Вообще, давай следовать нормальным практикам и использовать https://relishapp.com/waterlink/rspec-json-expectations/docs/json-expectations/match-unordered-json-matcher 
Вот пачка мэтчеров для json
А еще идеально использовать мэтчер схемы.
https://github.com/thoughtbot/json_matchers
Сами спеки сильно в этом случае сократятся

2020-09-24 09:57 UTC, vkurennov commented on app/controllers/api/v1/answers_controller.rb
> +      @answer = Answer.find(params[:id])
Если ресурс shallow, то так не получится, т.к. родительский в этом случае не загружается.

2020-10-01 17:52 UTC, dniman commented on app/controllers/api/v1/answers_controller.rb
> +      @answer = Answer.find(params[:id])
Я не понимаю, что тут от меня хотят. Мне сейчас shallow нужно убрать из routes.rb и обрабатывать полные маршруты?

2020-10-01 19:13 UTC, dniman commented on app/controllers/concerns/response.rb
> +module Response
Я не нашел ничего про рефлектор(

2020-10-02 06:26 UTC, IvanShamatov commented on app/controllers/api/v1/answers_controller.rb
> +      @answer = Answer.find(params[:id])
нет, я просто забыл, что тут shallow. Извини, что сбил с пути

2020-10-02 06:36 UTC, IvanShamatov commented on app/models/link.rb
> +  default_scope { order(id: :desc).order(:created_at) }
сделай другой скоуп, назови его как-нибудь и используй

2020-10-02 06:37 UTC, IvanShamatov commented on config/initializers/active_model_serializers.rb
> +Oj.optimize_rails
❤️

2020-10-02 06:38 UTC, IvanShamatov commented on spec/support/api_helper.rb
> +module ApiHelper
APIHelper

2020-10-02 06:40 UTC, IvanShamatov commented on app/serializers/question_serializer.rb
> +    object.files.map { |file| rails_blob_path(file, only_path: true) }
N+1 здесь не ловишь?

2020-10-02 06:40 UTC, IvanShamatov commented on app/serializers/answer_serializer.rb
> +    object.files.map { |file| rails_blob_path(file, only_path: true) }
вижу N+1

2020-10-02 06:41 UTC, IvanShamatov commented on app/controllers/concerns/response.rb
> +module Response
однако к API акроним с помощью рефлектора сделал

2020-10-02 06:44 UTC, dniman commented on app/serializers/question_serializer.rb
> +    object.files.map { |file| rails_blob_path(file, only_path: true) }
object.with_attached_files не работает

2020-10-02 06:45 UTC, dniman commented on app/serializers/question_serializer.rb
> +    object.files.map { |file| rails_blob_path(file, only_path: true) }
в самом контроллере добавил

2020-10-02 06:51 UTC, IvanShamatov commented on app/serializers/question_serializer.rb
> +    object.files.map { |file| rails_blob_path(file, only_path: true) }
принято

2020-10-03 17:31 UTC, merged